# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Harvesting Clouds
tagline:          'All about Private and Public Clouds'
description:      'A simple blog about all powerfull things about private and public clouds. Authored by <a href="https://twitter.com/20aman" target="_blank">@20aman</a>.'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Aman Sharma'
  url:            https://twitter.com/20aman

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/harvestingclouds
